# Generated by Django 5.2.8 on 2025-12-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cliente_id_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='produtos_ultima_compra',
            field=models.TextField(null=True),
        ),
    ]
